version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
        environment:
          DATABASE_URL: sqlite:./todo-subsecond.sqlite
    working_directory: ~/repo
    steps:
      - run:
          name: check version
          command: |
            node --version
            yarn --version
      - checkout
      - restore_cache:
          keys:
          - todo-subsecond-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: todo-subsecond-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn test
